apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-{{DEPLOYMENT}}
  namespace: {{NAMESPACE}}
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - {{NAMESPACE}}
    labelSelectors:
      app: {{DEPLOYMENT}}
  duration: "20s"
