"""
Export ML Results to Dashboard
Converts test results to dashboard-compatible format
"""

import json
import os
import glob

def export_curves_to_dashboard():
    """Export curve data to dashboard data file"""

    dashboard_path = "/root/Project/model-insights-dashboard/src/data"
    curve_data = {}

    # Process each version
    for version in ['v1', 'v2', 'v3']:
        version_dir = f"/root/Project/ML-based-Threat-aware-Auto-scaling-in-Kubernetes/results/test_results/{version}"

        if not os.path.exists(version_dir):
            continue

        curve_data[version] = {}

        # Find all curve files
        curve_files = glob.glob(os.path.join(version_dir, "*_curves.json"))

        for curve_file in curve_files:
            model_name = os.path.basename(curve_file).replace('_curves.json', '')

            with open(curve_file, 'r') as f:
                curves = json.load(f)
                curve_data[version][model_name] = curves

            print(f"✓ Loaded curves for {version}/{model_name}")

    # Save to dashboard
    output_file = os.path.join(dashboard_path, "curveData.ts")

    with open(output_file, 'w') as f:
        f.write("// Auto-generated curve data from ML models\n")
        f.write("// Generated by export_to_dashboard.py\n\n")
        f.write("export interface CurveData {\n")
        f.write("  roc: {\n")
        f.write("    fpr: number[];\n")
        f.write("    tpr: number[];\n")
        f.write("    auc: number;\n")
        f.write("  };\n")
        f.write("  pr: {\n")
        f.write("    precision: number[];\n")
        f.write("    recall: number[];\n")
        f.write("    auc: number;\n")
        f.write("  };\n")
        f.write("}\n\n")
        f.write("export const curveData: Record<string, Record<string, CurveData>> = ")
        f.write(json.dumps(curve_data, indent=2))
        f.write(";\n")

    print(f"\n✓ Curve data exported to: {output_file}")
    return curve_data

def export_training_history():
    """Export training history (for Autoencoder)"""

    dashboard_path = "/root/Project/model-insights-dashboard/src/data"
    history_data = {}

    for version in ['v1', 'v2', 'v3']:
        version_dir = f"/root/Project/ML-based-Threat-aware-Auto-scaling-in-Kubernetes/results/test_results/{version}"

        if not os.path.exists(version_dir):
            continue

        history_data[version] = {}

        # Find all training history files
        history_files = glob.glob(os.path.join(version_dir, "*_training_history.json"))

        for history_file in history_files:
            model_name = os.path.basename(history_file).replace('_training_history.json', '')

            with open(history_file, 'r') as f:
                history = json.load(f)
                history_data[version][model_name] = history

            print(f"✓ Loaded training history for {version}/{model_name}")

    # Save to dashboard
    output_file = os.path.join(dashboard_path, "trainingHistory.ts")

    with open(output_file, 'w') as f:
        f.write("// Auto-generated training history from ML models\n")
        f.write("// Generated by export_to_dashboard.py\n\n")
        f.write("export interface TrainingHistory {\n")
        f.write("  loss: number[];\n")
        f.write("  val_loss?: number[];\n")
        f.write("}\n\n")
        f.write("export const trainingHistory: Record<string, Record<string, TrainingHistory>> = ")
        f.write(json.dumps(history_data, indent=2))
        f.write(";\n")

    print(f"✓ Training history exported to: {output_file}")
    return history_data

def main():
    print("=" * 70)
    print("EXPORTING ML RESULTS TO DASHBOARD")
    print("=" * 70)

    # Export curve data
    print("\n[1/2] Exporting ROC/PR curves...")
    curve_data = export_curves_to_dashboard()

    # Export training history
    print("\n[2/2] Exporting training history...")
    history_data = export_training_history()

    print("\n" + "=" * 70)
    print("✅ EXPORT COMPLETE!")
    print("=" * 70)

    print("\nExported data:")
    print(f"  - Curve data: {len(curve_data)} versions")
    for version, models in curve_data.items():
        print(f"    • {version}: {len(models)} models")

    if history_data:
        print(f"  - Training history: {len(history_data)} versions")
        for version, models in history_data.items():
            print(f"    • {version}: {len(models)} models")

    print("\nNext step: Restart the dashboard to see the new visualizations!")

if __name__ == "__main__":
    main()
