apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-order
  namespace: ecommerce-test
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - ecommerce-test
    labelSelectors:
      app: order
  duration: "20s"
