apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Including all variant environment variable names for convenience
  MONGODB_AUTH_URI: "mongodb+srv://dpraveendesilva_db_user:6mR61Tyx1Ye6hLp2@cluster.3q6yccc.mongodb.net/k8sdb"
  MONGODB_PRODUCT_URI: "mongodb+srv://dpraveendesilva_db_user:6mR61Tyx1Ye6hLp2@cluster.3q6yccc.mongodb.net/k8sdb"
  MONGODB_ORDER_URI: "mongodb+srv://dpraveendesilva_db_user:6mR61Tyx1Ye6hLp2@cluster.3q6yccc.mongodb.net/k8sdb"
  JWT_SECRET: "JWT_SECRET"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
