apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-auth
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - ecommerce-test
  selector:
    matchLabels:
      app: auth
      environment: test
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-product
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - ecommerce-test
  selector:
    matchLabels:
      app: product
      environment: test
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-order
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - ecommerce-test
  selector:
    matchLabels:
      app: order
      environment: test
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-api-gateway
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - ecommerce-test
  selector:
    matchLabels:
      app: api-gateway
      environment: test
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
